### PR TITLE
Fix possible division by zero

### PR DESCRIPTION
**Pull request by Hoiss**
ch0 value of 0 is dangerous in calculateLuxf function.

### CODE REVIEW

**Comment by Hoiss** [comment]
Hmmm, did I do something wrong with this pull-request?
I just changed line 237 in Adafruit_TSL2591.cpp but it shows 2 conflicting files with changes not from me.

**Comment by ladyada** [comment]
maybe best to start over with a new fork and add your changes there!

**Comment by caternuson** [comment]
Yep. Looks like your fork was forked from this repo:
https://github.com/jocelyngirard/Adafruit_TSL2591_Library
which hasn't been touched in years. So your PR is based on super old code.

**Comment by Hoiss** [comment]
OK, no idea how that happened, sorry.
I will try it again...

**Pull request closed without merging**
