### PR TITLE
Add NPAI threshold

### PR DESCRIPTION
**Pull request by s-light**
- fix misleading names for threshold setter
- added NPAI threshold setter
- added extended interrupt test / example
- added print* Helper functions

### CODE REVIEW

**Comment by s-light** [comment]
i tested all three examples with a ItsyBitsy M4 Express and the TSL2591 Adafruit Module.
they all three compiled and worked fine.

in my next step i will try to create a example that uses the hardware interrupt to free the processor from polling.
This is the basis for the next step: my goal is to implement an auto-gain adjustment.

**Comment by s-light** [comment]
i have cleaned the library.properties conflict..
this way currently the version is not updated..

**Comment by caternuson** [comment]
Closing. This would need to be rebased on current library code. It would also be better to submit things in smaller separate pull requests.

**Comment by s-light** [comment]
ok.
if  i get any a project / any time again i will try to redo the pullrequest in smaller parts... no idea if / when this will happen..

**Pull request closed without merging**
