### PR TITLE
calculateLux return value in case of overflow

### PR DESCRIPTION
**Pull request by jaimealemany**
The original (0) value does not seem a good return value in case of overflow.
-1 seems better, as it is not a valid lux return value.

### CODE REVIEW

**Comment by Phoenix1747** [comment]
Why does 0 not look like a good return value? I think 0 is good enough, because there is never 0 light. But -1 seems to be much more distinct :D

**Comment by Phoenix1747** [comment]
By the way you should redo the `.github/PULL_REQUEST_TEMPLATE.md` file!

**Comment by jaimealemany** [comment]
Even if there was never 0 light, the calculation has 0 as a valid return - depending on the sensitivity and exposure time settings, it is a value to be expected. So 0 is a valid return, thus overflow has to be signaled some other way, imho.

**Comment by jaimealemany** [comment]
Great, thanks!

**Pull request merged**
