### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hoffmannjan**
fixed travis links

### CODE REVIEW

**Comment by ladyada** [comment]
@hoffmannjan please fix travis complaint too :)

**Comment by caternuson** [comment]
Looks like ESP32 is being a little stricter with the compiler flags. This one at least:
```
/home/travis/arduino_ide/libraries/Adafruit_Test_Library/Adafruit_TSL2591.cpp:326:64: error: 'y' may be used uninitialized in this function [-Werror=maybe-uninitialized]

   y |= read16(TSL2591_COMMAND_BIT | TSL2591_REGISTER_CHAN0_LOW);
```
seems worth fixing. Wonder if that `|=` is a typo? Should just be `=`?

**Comment by ladyada** [comment]
yes the compilers are getting pickier (which is good :) you can assign y = 0 beforehand, or when its instantiated.

**Comment by hoffmannjan** [comment]
yeah esp32 is especially picky ;), added fix in #31 
thanks @caternuson !

**Comment by hoffmannjan** [comment]
retriggered the build as It should passes with new master

**Pull request merged**
