### PR TITLE
Support for defining Wire implementation 

### PR DESCRIPTION
**Pull request by j0uni**
Just implementation to support to define TwoWire instance to use.

### CODE REVIEW

**Comment by ladyada** [comment]
hihi thank you! could you add the doxygen documentation so it passes travis?
https://travis-ci.com/adafruit/Adafruit_TSL2591_Library/jobs/274584666#L372

**Comment by ladyada** [comment]
thanks - what hardware did you test with?

**Comment by j0uni** [comment]
> thanks - what hardware did you test with?

ESP32, running smoothly. It is just a copy of the same implementation at your TSL2561 library.

**Comment by j0uni** [comment]
Thanks for adding this and your great work. Nice to help a bit.

**Comment by ladyada** [comment]
yay! thanks :)

**Pull request merged**
